### ISSUE TITLE
Any doc for building?

### ISSUE THREAD

**Issue by guotong1988** [zopefoundation/BTrees#105]
Build in my own Linux machine.
Thank you!

**Comment by jamadden** [comment]
There don't know of any specific documents fro building BTrees. 

BTrees is a simple CPython extension with no external dependencies. It lets `setuptools` handle all the details of compiling and linking. 

All you should need is an environment that can build CPython extensions. Usually this means a working C compiler and the Python development headers/libraries; depending on your system this can be a separate installation such as `apt-get install python-dev`.

Then from a BTrees clone, you should simply be able to type `pip install -e .` or `python setup.py build_ext -i` or similar.
