### ISSUE TITLE
TypeError: '<' not supported between instances of 'dict' and 'dict': Python3 

### ISSUE THREAD

**Issue by nazrulworld** [zopefoundation/BTrees#109]
BTrees.OOBTree.OOBTree
===================
I have used dict obj as key of OOBTree(), It is possible to assign value for the first time but later when I want to get value using that key, got the above error.
NB:  This is Python3 only problem

```
[15]: storage = OOBTree()

In [16]: key = {"k": "T"}

In [17]: storage[key] =  dict()

In [18]: len(storage)
Out[18]: 1

In [19]: storage.keys()[0]
Out[19]: {'k': 'T'}

In [20]: storage.get(key)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-20-de28bd731c0a> in <module>
----> 1 storage.get(key)

TypeError: '<' not supported between instances of 'dict' and 'dict'

In [21]: storage[key]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-21-5c1510f25f74> in <module>
----> 1 storage[key]

TypeError: '<' not supported between instances of 'dict' and 'dict'
```

**Comment by d-maurer** [comment]
Under Python 3, `dict` no longer supports comparison.
`BTrees` rely on full comparison support for its keys.
As a consequence, under Python 3, you can no longer uses `dict`s as keys
for `BTrees`.

A workaround might be that you derive a new class from `dict` and
define a comparison (`__le__`) for it. You must ensure that
it defines a total order. You can then use your new class as
`dict` replacement for `BTree` keys.

**Comment by nazrulworld** [comment]
@d-maurer Thank you so much for your helping. I will do close this issue soon.
