### ISSUE TITLE
readthedocs documentation update

### ISSUE THREAD

**Issue by azmeuk** [zopefoundation/BTrees#124]
Hi. The documentation code has been updated recently, but the documentation at [readthedocs](https://btrees.readthedocs.io/en/latest/) has not been updated.

Can someone plugs readthedocs so the documentation is updated each time a commit is pushed? I would gladly do it myself, but I do not have the authorizations to do so.

@jamadden The [project page](https://readthedocs.org/projects/btrees/) is telling me that maybe you do?

**Comment by jamadden** [comment]
Thanks for noticing the issue. The RTD integration was still using the old 'GitHub service,' not the new 'GitHub WebHook.' I've updated the hook and kicked off a build.

**Comment by azmeuk** [comment]
Thank you!
