### ISSUE TITLE
has_key raise KeyError

### ISSUE THREAD

**Issue by azmeuk** [zopefoundation/BTrees#125]
Hi. I think there might be an issue with the `has_key` method in persistent 4.6.1:

```python
>>> from BTrees.LOBTree import LOBTree
>>> a = LOBTree()
>>> a.has_key("invalid")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'invalid'
```

`has_key` is supposed to return a boolean, and never raise anything.

**Comment by azmeuk** [comment]
My bad. Strings are just not good keys for LOBtrees....

**Comment by jamadden** [comment]
The `in` operator has the behaviour of returning a boolean and not raising, even for invalid keys (with releases after https://github.com/zopefoundation/BTrees/pull/43/). That's because `in` is part of the language spec and should behave that way.
