### ISSUE TITLE
Change keys, values and items methods so they match python 3 dicts behavior

### ISSUE THREAD

**Issue by azmeuk** [zopefoundation/BTrees#129]
Back to python2 the `keys`, `values` and `items` methods on dictionaries [where returning collections of data](https://docs.python.org/2/library/stdtypes.html#dict.items) while `iterkeys`, `itervalues` and `iteritems` where returning iterators on those collections.
Now with python3, `iterkeys`, `itervalues` and `iteritems` have disappeared, and `keys`, `values` and `items` are [returning views on data](https://docs.python.org/3.8/library/stdtypes.html#dict.items).

I suppose the BTrees `keys`, `iterkeys` (and others) functions where first implemented in the python2 era and where trying to have an API similar to python2 dicts. Now that those days are long gone, what would you think of implementing a similar behavior, so using BTrees would still look like using regular python dicts?

Note that I do not know what that would imply about performances. Currently does `mybtree.keys()` is as fast as `list(mybtree.iterkeys())`?

**Comment by jamadden** [comment]
All those methods already return abstract collections ("views"), *not* lists or anything similar that requires materializing the entire contents) (and [are documented to do so](https://btrees.readthedocs.io/en/latest/api.html#BTrees.Interfaces.IMinimalDictionary.values)):
```pycon
In [1]: import BTrees

In [2]: bt = BTrees.OOBTree.BTree({'a': 1, 'b': 2})

In [3]: bt.keys()
Out[3]: <OOBTreeItems at 0x111072640>

In [4]: bt.values()
Out[4]: <OOBTreeItems at 0x111709e80>

In [5]: bt.items()
Out[5]: <OOBTreeItems at 0x11120fb80>
```

Those [return values are lazy](https://github.com/zopefoundation/BTrees/blob/ce69faf6d2648bdeab3022a9d2575a807db5c145/BTrees/_base.py#L1166) (almost by necessity — it's the most straightforward way to implement them).

**Comment by azmeuk** [comment]
Ok I had misunderstood how things works and I was mislead by several things:

- [_Tree.iterkeys](https://github.com/zopefoundation/BTrees/blob/master/BTrees/_base.py#L903), [_Tree.itervalues](https://github.com/zopefoundation/BTrees/blob/master/BTrees/_base.py#L1264) and [_Tree.iteritems](https://github.com/zopefoundation/BTrees/blob/master/BTrees/_base.py#L1272) return iterators on `_Tree.keys`, `_Tree.values` and `_Tree.items`. Iterators on lazy collections seem to be redundant as you said in #128, maybe it worth deprecate those methods?
- [_Bucket.iterkeys](https://github.com/zopefoundation/BTrees/blob/ce69faf6d2648bdeab3022a9d2575a807db5c145/BTrees/_base.py#L194), [_Bucket.itervalues](https://github.com/zopefoundation/BTrees/blob/ce69faf6d2648bdeab3022a9d2575a807db5c145/BTrees/_base.py#L390) and [_Bucket.iteritems](https://github.com/zopefoundation/BTrees/blob/ce69faf6d2648bdeab3022a9d2575a807db5c145/BTrees/_base.py#L400) return generators on `_Bucket.keys`, `_Bucket.values` and `_Bucket.items`, that all return lists.

**Comment by d-maurer** [comment]
Éloi Rivard wrote at 2020-3-18 03:32 -0700:
>Back to python2 the `keys`, `values` and `items` methods on dictionaries [where returning collections of data](https://docs.python.org/2/library/stdtypes.html#dict.items) while `iterkeys`, `itervalues` and `iteritems` where returning iterators on those collections.

>Now with python3, `iterkeys`, `itervalues` and `iteritems` have disappeared, and `keys`, `values` and `items` are [returning views on data](https://docs.python.org/3.8/library/stdtypes.html#dict.items).

>

>I suppose the BTrees `keys`, `iterkeys` (and others) functions where first implemented in the python2 era and where trying to have an API similar to python2 dicts.

There are two types of "BTree"s: real trees and buckets.
For real trees, the "keys", "values" and "items" have always returned
iterators (similar to Python3' equivalent functions).
