### ISSUE TITLE
Allowing multiple values for a single key in BTree?

### ISSUE THREAD

**Issue by alejandroarmas** [zopefoundation/BTrees#148]
Sorry if this has already been answered but is there a way to override the `insert` method in `IIBTree()` to enable multiple values per key?

I wanted to implement an index in my Databases course and I wanted to make sure that selection query would return all values within a certain range and I'm assuming that sometimes those queries are going to encompass records whose attribute being queried are not unique. I'm imagining that insert is causing a problem for that.

Per the doc.
>insert(key)[source]
>Add the key (value) to the set.
>If the key was already in the set, return 0, otherwise return 1.

 Anything helps thanks!

@jamadden

**Comment by mwatts15** [comment]
@alejandroarmas If I understand correctly, you actually want to use an IOBTree. What object you store at that point is up to you, but the Bucket type may be a good candidate.

**Comment by alejandroarmas** [comment]
Oh so if I'm understanding this correctly, the `IOBTree` is used to hold all the pointers to intermediate nodes and the leaf nodes are only of `IOBucket` type? Is there any way you could you show me a simple example?

I'm toying with:
```python
bucket = IOBucket()
bucket.update({1:2}) 
```
I didn't know how else to add another item into bucket with the same key either but I was thinking of inserting those buckets as the leafs in my Tree. Maybe I'm just confusing the concepts.

**Comment by d-maurer** [comment]
Alejandro Armas wrote at 2021-1-24 21:03 -0800:
>Oh so if I'm understanding this correctly, the `IOBTree` is used to hold all the pointers to intermediate nodes and the leaf nodes are only of `IOBucket` type? Is there any way you could you show me a simple example?
>
>I'm toying with:
>```python
>bucket = IOBucket()
>bucket.update({1:2})
>```
>I didn't know how else to add another item into bucket with the same key either but I was thinking of inserting those buckets as the leafs in my Tree. Maybe I'm just confusing the concepts.

"Bucket"s support a large part of the mapping protocol,
among others subscription, i.e. "bucket[key] = value".

**Comment by alejandroarmas** [comment]
@d-maurer  Thank you for the clarification. I'm trying to my best to read the docs so I apologize for these silly questions, what should I do if I wanted to have multiple buckets with the same key pointing to multiple values? [This](https://www.cs.usfca.edu/~galles/visualization/BPlusTree.html) visualization is what I am trying to perform with the `insert` method in the `IOBtree` class.

**Comment by d-maurer** [comment]
Alejandro Armas wrote at 2021-1-25 00:08 -0800:
>@d-maurer  Thank you for the clarification. I'm trying to my best to read the docs so I apologize for these silly questions, what should I do if I wanted to have multiple buckets with the same key pointing to multiple values? [This](https://www.cs.usfca.edu/~galles/visualization/BPlusTree.html) visualization is what I am trying to perform with the `insert` method in the `IOBtree` class.

I do not understand what you would like to perform: the link you
presented seems to interactively visualize the B+ tree structure after
a sequences of inserts and deletes. It does not show a single key with
different values.

Note that the *Tree classes already implement some kind of
(unbalanced) B+ tree.

If you want to associate multiple values with the same key,
you combine your multiple values into a single one (e.g. via a tuple)
and associate that one with the key.

**Comment by jamadden** [comment]
Closing because it's been answered.
