### ISSUE TITLE
Release 4.7.3

### ISSUE THREAD

**Issue by azmeuk** [zopefoundation/BTrees#149]
There are some changes waiting to be released for half a year now. What do you think about releasing version `4.7.3`?

**Comment by jamadden** [comment]
I think we'll need to do the work to move off of Travis CI and onto github actions first, or we won't have any binary wheels uploaded. We rely on Travis CI to build the binary wheels for linux and macOS, but Travis CI has stopped working.

Maybe that's not a big deal, Linux users generally have compilers available and macOS users often do too. The Windows wheels are built by appveyor and that should still be working.

**Comment by jamadden** [comment]
4.8.0 has been released to PyPI.
