### ISSUE TITLE
Can we move to the src/ layout?

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/BTrees#155]
As with https://github.com/zopefoundation/persistent/issues/158

I was just bitten by one of the problems with having the directory in the root while trying to bring up the manylinux aarch64 builds. (Long story short, 'pip install BTrees' and using a git clone as the working directory are incompatible — the local directory shadows the installed version. You wind up only getting the pure-Python implementation because the shared libraries can't be found in `./BTrees/`.)

**Comment by freddrake** [comment]
My earlier comments about tracking git history across a rename aside, when there's a concrete reason that only the src layout is usable, it's time to migrate.

**Comment by icemac** [comment]
Yes please move to the `src/` layout. We've agreed to use it as default for all zopefoundation repositories. See https://github.com/zopefoundation/meta/issues/29

**Comment by jamadden** [comment]
I'd hope to merge #154 first (so we have working *IX CI), and them make a PR that moves to `src/`, if anyone is interested in taking a look.
