### ISSUE TITLE
Convert to meta/config

### ISSUE THREAD

**Issue by icemac** [zopefoundation/BTrees#176]
As this repository already runs the tests on GHA, it should be relatively easy to use `meta/config` to generate the configuration. Additionally we would get aarch wheels this way.

**Comment by mwatts15** [comment]
@icemac, could you add some detail? I, at least, don't know what "meta/config" is, how it relates to aarch wheels, or why it's desirable to have them.

**Comment by icemac** [comment]
`meta/config` is our configuration framework for the repositories, see https://github.com/zopefoundation/meta/tree/master/config. aarch wheels where requested for different repositories several times. Having them here would at least speed up the build for other aarch wheels depending on `BTrees`.
