### ISSUE TITLE
Binary wheels?

### ISSUE THREAD

**Issue by fgregg** [zopefoundation/BTrees#26]
Would it be possible to have binary wheels mac and windows on pypi? I'd be happy to build them or set up up scripts for appveyor and travis-ci to build them for you.

**Comment by mgedmin** [comment]
This sounds like an excellent idea to me.

**Comment by jamadden** [comment]
FWIW, I also think BTrees meet the criteria to be distributed as [manylinux wheels](https://www.python.org/dev/peps/pep-0513/). Can those be produced on Travis too?

**Comment by fgregg** [comment]
#27 builds Mac OS X wheels on travis and deploys them to pypi. The same approach is available for windows using appveyor. https://github.com/datamade/pylbfgs/blob/master/appveyor.yml

Would that be welcome here? It seems like there is also some dedicated zope infrastructure for building Window eggs, but there hasn't been movement to have that infrastructure build wheels.

**Comment by fgregg** [comment]
@jamadden I think that manylinux wheels can be built on travis, but I don't know how. I kind of expect that the infrastructure for building manylinux wheels will get better quickly, so I'd be tempted to wait a bit.

**Comment by tseaver** [comment]
@jamadden https://github.com/pypa/python-manylinux-demo demonstrates building `manylinux` wheels on Travis (including welding in external shared libs ?!).

**Comment by jamadden** [comment]
@tseaver Sadly, building manylinux wheels uses docker which requires sudo access (so the old, slow infrastructure). It's probably not worth changing that in BTrees (slow down all commit checks), as quickly as they build for end-users on linux, I'd guess.

**Comment by tseaver** [comment]
@jamadden Given how long BTrees tests take to run (4+ minutes even with `sudo: false`), the extra time might not be all that relevant.

**Comment by tseaver** [comment]
> The same approach is available for windows using appveyor. https://github.com/datamade/pylbfgs/blob/master/appveyor.yml
>
> Would that be welcome here? It seems like there is also some dedicated zope infrastructure for building Window eggs, but there hasn't been movement to have that infrastructure build wheels.

@fgregg I wouldn't object to reviewing / merging a Windows-wheels-via-appveyor PR.  The current Winbot is increasingly difficult for us to maintain (we can't even manage to get it to quit running failing Python 2.5 tests!)

**Comment by fgregg** [comment]
Here's a PR for the appveyor script. https://github.com/zopefoundation/BTrees/pull/30

**Comment by mgedmin** [comment]
It is my deepest desire to replace the current Windows VM that builds eggs for Pythons up to 3.2 with Appveyor building wheels (and eggs too, for legacy reasons) for Pythons up to 3.5.

**Comment by fgregg** [comment]
I think we can close this issue now?

**Comment by tseaver** [comment]
We probably shouldn't close it until after we make a 4.3.0 release and see the wheels show up automagically on PyPI.

**Comment by fgregg** [comment]
Just as an FYI, do you you know when you might cut a 4.3.0 release?

**Comment by tseaver** [comment]
4.3.0 [released](https://pypi.python.org/pypi/BTrees/4.3.0/)

**Comment by tseaver** [comment]
@fgregg The Mac builds on Travis failed for the 4.3.0 tag:

- https://travis-ci.org/zopefoundation/BTrees/jobs/129286691
- https://travis-ci.org/zopefoundation/BTrees/jobs/129286693

**Comment by fgregg** [comment]
It looks like the PYPIPASSWORD encrypted variable was not set completely correctly

https://docs.travis-ci.com/user/environment-variables/#Encrypting-Variables-Using-a-Public-Key

you'll need to run a command like

`travis encrypt PYPIPASSWORD=password_for_zope.wheelbuilder`

you'll get something that looks like 

```
  secure: "fB9vYiXkZluFCGw+gE4yg0ANbCmBcE5mzGZmvRNwMbI2/6RgEovCD+9w5kM6vqHY25sj3zIKeXervqKEVIZ5+2nmN/uOY86a60pbZ6Tf2tABe2iMzJya38US2rEydI8p3VCxdI0eoQ3TaXd0qNJy4SyqDucoMxi/SxeewlaIs3U="
```

replace https://github.com/zopefoundation/BTrees/blob/master/.travis.yml#L47 and push another tag.

**Comment by fgregg** [comment]
Window wheels are building! https://pypi.python.org/pypi/BTrees

**Comment by tseaver** [comment]
WOOT!

**Comment by fgregg** [comment]
@mgedmin do you think you could help with the travis PYPIPASSWORD

**Comment by mgedmin** [comment]
I'm guessing I encrypted just the password, without the variable name in https://github.com/zopefoundation/BTrees/pull/27#issuecomment-200209227.  Here's a new attempt, in the form of `PYPIPASSWORD=thepassword`, with a trailing newline:
```
  secure: "CpYDbVb6YOyIAnCcvBEiDLeYmNhfDDqJosIV0NussN9dNe1hsfHQK98evAEe9F4kXuWo6SmmtT0uX2RXOojB5If/z7sAcXSDaGWCMJK0FY98sWL2DCRtb1/O1puo/uvn3RJlpe4bkxQoyFCKjpWaTJOM+NSEt7YbTTTdCpG7/zU="
```
BTW @tseaver, can you read https://github.com/zopefoundation/BTrees/pull/27#issuecomment-200208969 successfully?

**Comment by tseaver** [comment]
@mgedmin I can read / decrypt that message.

**Comment by fgregg** [comment]
This ready to close?
