### ISSUE TITLE
Can't build/install BTrees because of a strange compilation issue

### ISSUE THREAD

**Issue by chubin** [zopefoundation/BTrees#41]
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/opt/lib/python2.7/site-packages/ZODB3-3.9.7-py2.7-linux-x86_64.egg -I/opt/include/python2.7 -c BTrees/_OOBTree.c -o build/temp.linux-x86_64-2.7/BTrees/_OOBTree.o
    In file included from BTrees/BTreeModuleTemplate.c:420:0,
                     from BTrees/_OOBTree.c:39:
    BTrees/BTreeTemplate.c: In function ‘_BTree_set’:
    BTrees/BTreeTemplate.c:736:5: warning: implicit declaration of function ‘PER_READCURRENT’ [-Wimplicit-function-declaration]
         PER_READCURRENT(self, goto Error);
         ^
    BTrees/BTreeTemplate.c:736:27: error: expected expression before ‘goto’
         PER_READCURRENT(self, goto Error);
                               ^
    error: command 'gcc' failed with exit status 1

**Comment by tseaver** [comment]
The include path does not contain the current `persistent` headers:  it looks as though you are building against a much older version of ZODB than current (`ZODB3-3.9.7` is almost six years old!). ZODB3 had older versions of`persistent` and `BTrees` embedded.

**Comment by chubin** [comment]
Does it mean, that if I take the newest version of ZODB3, I don't need BTrees (external module) at all, because it is already embedded?

**Comment by chubin** [comment]
I have uninstalled ZODB3 and installed it again (the new version) and in this case it was successful. But, JFYI, you can't upgrade ZODB3 using pip install -U ZODB3 because of this bug.

**Comment by tseaver** [comment]
The `ZODB3` package has split ou into `persistent`, `BTrees`, and `ZODB` (no `3`).
