### ISSUE TITLE
hiccup building window wheels

### ISSUE THREAD

**Issue by fgregg** [zopefoundation/BTrees#59]
It seems like there was some sort of unlogged problem building the window wheels for the last release. @mgedmin would you mind restarting this build: https://ci.appveyor.com/project/mgedmin/btrees/build/1.0.60

**Comment by fgregg** [comment]
Actually zope.interface seems to have same problem. Maybe we don't have the right password?

**Comment by fgregg** [comment]
And persistent https://ci.appveyor.com/project/mgedmin/persistent/build/1.0.32/job/0vcfg3tig0wqwkcj

**Comment by mgedmin** [comment]
There was that [Travis password leak](https://blog.travis-ci.com/2016-11-23-security-vulnerability-environment-variables/), after which we changed the PyPI password for zope.wheelbuilder, but then I dropped the ball and didn't change any of the Appveyor files.

I don't remember how you go about encrypting env vars for Appveyor.

This ought to be documented somewhere.  *sigh*

**Comment by mgedmin** [comment]
Ok, the procedure is

- go to https://ci.appveyor.com/tools/encrypt
- paste the zope.wheelbuilder PyPI password into the text box
- hit Encrypt
- copy the encrypted value (`UcdTh6W78cRLVGfKRFoa5A==` into all the `appveyor.yml`s)

Now, is it possible somehow to retroactively build old tags but tell Appveyor to use the new encrypted value?

**Comment by mgedmin** [comment]
I'm going to change the `appveyor.yml`s to always build wheels, so that people could upload them manually in the future if something like this happens again.

I would very much like to know how to ask twine not to hang for an hour if the password is wrong.

**Comment by mgedmin** [comment]
> I would very much like to know how to ask twine not to hang for an hour if the password is wrong.

Filed https://github.com/pypa/twine/issues/224.

**Comment by mgedmin** [comment]
Hmm.  I dropped the ball, but Tres did update the password in `appveyor.yml`: https://github.com/zopefoundation/BTrees/commit/585ec7e58be22667355955bd8aa4fd1392a32c5e.

What went wrong?

**Comment by mgedmin** [comment]
By a lucky coincidence BTrees had no commits since the last tag (not even the usual post-commit version bump), so I can upload the wheels produced by [this Appveyor run](https://ci.appveyor.com/project/mgedmin/btrees/build/1.0.77) to PyPI manually.

The other affected packages (persistent, zope.interface, zope.index) have other commits, so no wheels until somebody makes a new release.

**Comment by mgedmin** [comment]
BTrees 4.4.0 wheels uploaded to PyPI.

Also, I just came up with a scheme to upload missing persistent/zope.interface/zope.index wheels:

- create a temporary branch based on the tag
- modify the credentials in appveyor.yml
- make the 'twine upload' unconditional
- better yet, change the check to upload iff `setup.py --version` does not contain `dev`
- commit and push
- wait for appveyor to build and upload
- remove the temporary branch

**Comment by mgedmin** [comment]
Ok, I'm attempting that thing for zope.interface: https://ci.appveyor.com/project/mgedmin/zope-interface/build/1.0.105

The builds should run in about an hour (Appveyor's free tier is slow! maybe ZopeFoundation would like to shell out for a paid account?).

**Comment by mgedmin** [comment]
I've queued a build for persistent too: https://ci.appveyor.com/project/mgedmin/persistent/build/1.0.63

I've no plans to build zope.index wheels, but I can, if somebody asks (preferably after they fix https://github.com/zopefoundation/zope.index/issues/9).

**Comment by mgedmin** [comment]
zope.interface wheels have been built and uploaded to PyPI successfully.

persistent wheels for 32-bit Python have been built and uploaded to PyPI successfully.  Wheels for 64-bit Python are missing because of test failures (what were fixed in master *after( the last release).

**Comment by fgregg** [comment]
My goodness! thank you so much @mgedmin !
