### ISSUE TITLE
Docs for Length module?

### ISSUE THREAD

**Issue by smheidrich** [zopefoundation/BTrees#63]
Why isn't there any documentation for the ``BTrees.Length.Length`` class? Is that because it doesn't have an interface and the documentation is supposed to contain only interfaces? Is ``Length`` even an official part of ``BTrees`` if it's undocumented? It is mentioned in the ZODB docs, that's why I'm wondering...

**Comment by tseaver** [comment]
@smheidrich Nothing so intentional:  It is just an oversight.  Please feel free to submit a PR adding a new "utilities" section to https://raw.githubusercontent.com/zopefoundation/BTrees/master/docs/api.rst, using the `autoclass` directive to pull in `Length`.

**Comment by tseaver** [comment]
Via #64.
