### ISSUE TITLE
BTrees 4.4 breaks a test in zope.index

### ISSUE THREAD

**Issue by icemac** [zopefoundation/BTrees#65]
I had to pin down to `BTrees < 4.4` in `zope.index` to get rid of the test failure.
See zopefoundation/zope.index#10.

I am not sure if it is a problem within `BTrees` or if `zope.index` has to be changed.
Any help is welcome.

**Comment by tseaver** [comment]
Fixed via https://github.com/zopefoundation/zope.index/pull/12
