### ISSUE TITLE
Add linux wheels for 4.5.0 release to PyPI

### ISSUE THREAD

**Issue by icemac** [zopefoundation/BTrees#86]
There are currently only the wheels for windows but not for linux at PyPI: https://pypi.org/project/BTrees/4.5.0/#files

**Comment by mgedmin** [comment]
1. LOL
2. You can always push a one-off branch based on the 4.5.0 tag that has no code changes but modifies .travis-ci.yml skip the "is this a tag?" check to build and upload manylinux wheels for that release, then delete that branch.

**Comment by icemac** [comment]
@mgedmin Thank you for the tip, https://pypi.org/project/BTrees/4.5.0/#files now has the missing wheels.
