### ISSUE TITLE
IFBTree and LFBTree raise "TypeError: expected integer key" for .values(min=<float>, max=<float>)

### ISSUE THREAD

**Issue by Kevin-Prichard** [zopefoundation/BTrees#87]
The interface for IFBTree.values and LFBTree.values led me to believe I could obtain an iterator for entries with float values falling between two points, min=<float> and max=<float>.

However, it throws 'expected integer key' when using min or max.  Perhaps I misunderstand the interface?

To reproduce, paste the following to Python >=3.4 repl:

```
from BTrees.LFBTree import LFBTree
import random

lft = LFBTree()
for i in range(10000):
    lft.update({random.randint(a=1, b=9999999): random.random()})

vals = lft.values(min=0.1, max=0.2)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: expected integer key
```

**Comment by jamadden** [comment]
BTrees are sorted by *key*, not value. The arguments to the `values` function allow you to get the subset of values whose keys are in the given range. Hence the arguments must be the type accepted for keys.

**Comment by Kevin-Prichard** [comment]
Okay, understood.  Thanks for the swift response.

I suppose what I'm looking for, then, is a Btree implemented with float as the key type.  So that I can perform inexact min/max range searches on floating point values.

Has anything like this been requested for BTrees?  More importantly, do you believe it is possible?

**Comment by tseaver** [comment]
As long as all the keys are floats, you could use an `OOBTree`:

```python
>>> from BTrees.OOBTree import OOBTree
>>> tree = OOBTree()
>>> 
>>> tree[.3] = 'wwww'
>>> tree[.4] = 'xxxx'
>>> tree[.5] = 'yyyy'
>>> tree[.6] = 'zzzz'
>>> list(tree.values(min=.35, max=.55))
['xxxx', 'yyyy']
```

**Comment by Kevin-Prichard** [comment]
That class I did not think of trying.  Thanks very much, @tseaver, I will see how it works for me.
