### ISSUE TITLE
4.1.1 test failure on 32-bit Linux system with python 3.4

### ISSUE THREAD

**Issue by jamesjer** [zopefoundation/BTrees#9]
Release 4.1.1 fails one test on 32-bit Linux systems with python 3.4:

ERROR: test_extremes (BTrees.tests.test_OLBTree.OLBTreeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/python-BTrees-4.1.1/python3-BTrees-4.1.1/BTrees/tests/test_OLBTree.py", line 118, in test_extremes
    btree['SMALLEST_64_BITS'] = SMALLEST_64_BITS
OverflowError: Python int too large to convert to C long

**Comment by tseaver** [comment]
Can you re-try with the trunk?  I don't have a 32-bit machine to play with ATM.
